update

diff --git a/.github/workflows/makerun.yml b/.github/workflows/makerun.yml
--- a/.github/workflows/makerun.yml
+++ b/.github/workflows/makerun.yml
@@ -1,4 +1,4 @@
-name: Create Passwall Self-Extracting Package
+name: Create Passwall Self-Extracting Packages
 
 on:
   push:
@@ -21,42 +21,55 @@ jobs:
         run: |
           mkdir -p downloads
           cd downloads
-          curl -LO $(curl -s https://api.github.com/repos/xiaorouji/openwrt-passwall/releases/latest | grep -oP '"browser_download_url":\s*".*passwall_packages_ipk_x86_64.zip"' | cut -d '"' -f 4)
-          curl -LO $(curl -s https://api.github.com/repos/xiaorouji/openwrt-passwall/releases/latest | grep -oP '"browser_download_url":\s*".*luci-19.07.*\.ipk"' | head -1 | cut -d '"' -f 4)
-          curl -LO $(curl -s https://api.github.com/repos/xiaorouji/openwrt-passwall/releases/latest | grep -oP '"browser_download_url":\s*".*luci-19.07.*\.ipk"' | tail -1 | cut -d '"' -f 4)
-
-      - name: Organize files
+          curl -LO $(curl -s https://api.github.com/repos/xiaorouji/openwrt-passwall/releases/latest | grep -oP "\"browser_download_url\":\s*\".*passwall_packages_ipk_x86_64\.zip\"" | cut -d '"' -f 4)
+          curl -LO $(curl -s https://api.github.com/repos/xiaorouji/openwrt-passwall/releases/latest | grep -oP "\"browser_download_url\":\s*\".*passwall_packages_ipk_aarch64_cortex-a53\.zip\"" | cut -d '"' -f 4)
+          curl -LO $(curl -s https://api.github.com/repos/xiaorouji/openwrt-passwall/releases/latest | grep -oP '\"browser_download_url\":\s*\".*luci-19.07.*\\.ipk\"' | head -1 | cut -d '"' -f 4)
+          curl -LO $(curl -s https://api.github.com/repos/xiaorouji/openwrt-passwall/releases/latest | grep -oP '\"browser_download_url\":\s*\".*luci-19.07.*\\.ipk\"' | tail -1 | cut -d '"' -f 4
+      
+      - name: Organize files for x86_64
         run: |
-          mkdir -p passwall/depends passwall/main
-          unzip downloads/passwall_packages_ipk_x86_64.zip -d passwall/depends
+          mkdir -p passwall_x86_64/depends passwall_x86_64/main
+          unzip downloads/passwall_packages_ipk_x86_64.zip -d passwall_x86_64/depends
           rm downloads/passwall_packages_ipk_x86_64.zip
-          mv downloads/luci-19.07*.ipk passwall/main/
+          cp downloads/luci-19.07*.ipk passwall_x86_64/main/
 
-      - name: Create install.sh script
+      - name: Organize files for aarch64_cortex-a53
         run: |
-          cat <<EOF > passwall/install.sh
-          #!/bin/sh
-          opkg update
-          if [ $? -ne 0 ]; then
-              echo "update failed。"
-              exit 1
-          fi
-          opkg install depends/*.ipk
-          opkg install main/*.ipk
-          EOF
-          chmod +x passwall/install.sh
+          mkdir -p passwall_aarch64/depends passwall_aarch64/main
+          unzip downloads/passwall_packages_ipk_aarch64_cortex-a53.zip -d passwall_aarch64/depends
+          rm downloads/passwall_packages_ipk_aarch64_cortex-a53.zip
+          cp downloads/luci-19.07*.ipk passwall_aarch64/main/
 
-      - name: Move passwall to makeself directory
-        run: mv passwall makeself/
+      - name: Create install.sh scripts
+        run: |
+          for arch in x86_64 aarch64; do
+            cat <<EOF > passwall_${arch}/install.sh
+            #!/bin/sh
+            opkg update
+            if [ $? -ne 0 ]; then
+                echo "update failed."
+                exit 1
+            fi
+            opkg install depends/*.ipk
+            opkg install main/*.ipk
+            EOF
+            chmod +x passwall_${arch}/install.sh
+          done
 
-      - name: Create self-extracting package
+      - name: Move passwall directories to makeself
+        run: |
+          mv passwall_x86_64 makeself/
+          mv passwall_aarch64 makeself/
+
+      - name: Create self-extracting packages
         run: |
           cd makeself
-          ./makeself.sh passwall/ passwall.run "by github action" ./install.sh
+          ./makeself.sh passwall_x86_64/ passwall_x86_64.run "by github action" ./install.sh
+          ./makeself.sh passwall_aarch64/ passwall_aarch64.run "by github action" ./install.sh
 
-      - name: Check file size
+      - name: Check file sizes
         run: |
-          ls -lh makeself/passwall.run
+          ls -lh makeself/passwall_*.run
 
       - name: Preparing release name
         run: |
@@ -66,11 +79,12 @@ jobs:
       - name: Fetch latest release details
         id: fetch_release_details
         run: |
+          extra_content="![GitHub Release](https://img.shields.io/github/v/release/wukongdaily/ActionDemo?style=for-the-badge&logoSize=amg&labelColor=%23FFBF00&color=%2300C598)"
           release_notes=$(curl -s https://api.github.com/repos/xiaorouji/openwrt-passwall/releases/latest | jq -r '.body')
           if [ -z "$release_notes" ]; then
             release_notes="No release notes available."
           fi
-          echo "$release_notes" > release_notes.md
+          echo -e "$extra_content\n\n$release_notes" > release_notes.md
 
       - name: Print release notes
         run: |
@@ -90,7 +104,7 @@ jobs:
         uses: softprops/action-gh-release@v2.1.0
         with:
           tag_name: RunFilesBuilder
-          files: ${{ github.workspace }}/makeself/*.run
+          files: makeself/passwall_*.run
           token: ${{ secrets.GITHUB_TOKEN }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
