Update t.yml

diff --git a/.github/workflows/t.yml b/.github/workflows/t.yml
--- a/.github/workflows/t.yml
+++ b/.github/workflows/t.yml
@@ -1,53 +1,116 @@
-name: Download IPK Files
+#=================================================
+# https://github.com/wukongdaily/RunFilesBuilder
+# Description: Build RunFiles using GitHub Actions
+# Lisence: MIT
+# Author: wukongdaily
+# Blog: wkdaily.cpolar.top
+#=================================================
+
+name: Make OpenClash run files 
 
 on:
   workflow_dispatch:
-    inputs:
-      openwrt_package:
-        description: '请输入 OpenWrt 的包版本（如 packages-24.10）'
-        required: true
-        default: 'packages-24.10'
 
 jobs:
-  download_ipks:
+  build:
+    if: ${{ github.repository == 'wukongdaily/RunFilesBuilder' || github.event_name == 'workflow_dispatch' }}
     runs-on: ubuntu-22.04
+
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-
-      - name: Install wget
-        run: sudo apt-get install -y wget
-
-      - name: Download IPK files
+      - name: Create OpenClash & openclash directory for git & ipk
+        run: mkdir -p OpenClash openclash-x86 openclash-a53
+        
+      - name: Checkout package branch to OpenClash directory
+        uses: actions/checkout@v4
+        with:
+          repository: vernesong/OpenClash
+          path: OpenClash
+          ref: package
+          
+      - name: Copy latest openclash IPK to openclash directory
         run: |
-          #!/bin/bash
+          cp OpenClash/master/*.ipk openclash-x86
+          cp OpenClash/master/*.ipk openclash-a53
 
-          # 目标文件服务器的 URL
-          BASE_URL="https://dl.openwrt.ai/packages-24.10/${{ github.event.inputs.openwrt_package }}/x86_64/kiddin9/"
+      - name: Get version info
+        id: extract_version
+        run: |
+          first_line=$(head -n 1 OpenClash/master/version)
+          echo "version=$first_line" >> $GITHUB_ENV
 
-          # 需要匹配的文件名前缀列表
-          FILE_PREFIXES=("chinadns-ng" "dns2socks" "hysteria" "ipt2socks" "microsocks" "mosdns" "naiveproxy" "redsocks2" "shadowsocksr-libev" "shadowsocks-rust" "shadow-tls" "simple-obfs-client" "tcping" "trojan" "tuic-client" "v2ray-plugin" "xray-core")
+      - name: Create Meta directory for git
+        run: mkdir Meta
+      
+      - name: Checkout core branch to Meta directory
+        uses: actions/checkout@v4
+        with:
+          repository: vernesong/OpenClash
+          path: Meta
+          ref: core
+      
+      - name: list all cores on core branch
+        run: ls Meta/master/meta
 
-          # 使用 wget 获取目录页面
-          wget -qO- "$BASE_URL" | \
-              # 循环检查每个文件名前缀
-              while read -r LINE; do
-                  # 遍历所有文件名前缀，检查文件是否匹配
-                  for PREFIX in "${FILE_PREFIXES[@]}"; do
-                      # 使用 grep 检查文件名是否包含在文件列表中
-                      if [[ "$LINE" == *"$PREFIX"* ]]; then
-                          # 提取 href 中的文件名部分
-                          FILE=$(echo "$LINE" | grep -oP 'href="\K[^"]*')
-                          
-                          # 生成完整的文件 URL
-                          FILE_URL="${BASE_URL}${FILE}"
-                          
-                          # 打印文件 URL
-                          echo "Found file: $FILE_URL"
-                          
-                          # 下载文件到指定目录
-                          wget "$FILE_URL" -P ./downloads/  # 下载到当前目录下的 downloads 文件夹
-                      fi
-                  done
-              done
-        shell: bash
+      - name: Copy latest meta core to openclash directory
+        run: |
+          tar -xzvf Meta/master/meta/clash-linux-amd64.tar.gz -C openclash-x86
+          tar -xzvf Meta/master/meta/clash-linux-arm64.tar.gz -C openclash-a53
+          mv openclash-x86/clash openclash-x86/clash_meta
+          mv openclash-a53/clash openclash-a53/clash_meta
+          ls openclash-x86
+          ls openclash-a53
+
+      - name: Create install.sh script save to openclash directory
+        run: |
+          cat << 'EOF' > openclash-x86/install.sh
+          opkg update
+          if [ $? -ne 0 ]; then
+              echo "update failed。"
+              exit 1
+          fi
+          opkg install *.ipk || exit 1
+          mv clash_meta /etc/openclash/core/
+          sleep 10s
+          ifconfig br-lan > /dev/null 2>&1
+          if [ $? -ne 0 ]; then
+              echo "接口错误，重启网络。"
+              /etc/init.d/network restart
+              echo "重启完毕"
+              exit 0
+          fi
+          EOF
+          chmod +x openclash-x86/install.sh
+          cp openclash-x86/install.sh openclash-a53/install.sh
+          chmod +x openclash-a53/install.sh
+
+      - name: Clone makeself repository for self-extracting installer
+        run: | 
+          git clone https://github.com/megastep/makeself.git
+
+      
+      - name: move openclash directory to makeself & create run
+        run: |
+          mv openclash-x86 makeself/
+          mv openclash-a53 makeself/
+          cd makeself
+          ./makeself.sh openclash-x86/ openclash-x86-64-${{ env.version }}.run "by github action" ./install.sh
+          ./makeself.sh openclash-a53/ openclash-aarch64_cortex-a53-${{ env.version }}.run "by github action" ./install.sh
+
+      - name: Generate new tag & release
+        uses: softprops/action-gh-release@master
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ env.version }}
+          target_commitish: ${{ github.ref_name }}
+          prerelease: false
+          body: "![Github](https://img.shields.io/badge/OpenClash.run-123456?logo=github&logoColor=fff&labelColor=red&style=for-the-badge) [![Github](https://img.shields.io/badge/国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge)](https://wkdaily.cpolar.top/archives/1) ![GitHub Downloads (all assets, specific tag)](https://img.shields.io/github/downloads/wukongdaily/RunFilesBuilder/${{ env.version }}/total?style=for-the-badge&labelColor=black&color=%2325c2a0)"
+
+      - name: Upload run files as release assets
+        uses: softprops/action-gh-release@v2.1.0
+        with:
+          tag_name: ${{ env.version }}
+          files: makeself/*.run
+          token: ${{ secrets.GITHUB_TOKEN }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
